def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any

    tools {
        jdk "JDK17"
        maven "MAVEN3.9"
    }

    environment {
        cluster = "vproappProd"
        service = "vprofileapptasknew-service-prod"
    }

    stages {                              
        stage("Deploy to Prod ECS") {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }
        }
    }

    post {
        always {
            echo 'Slack Notifications.'

            slackSend(
                channel: '#devopscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\nMore info at: ${env.BUILD_URL}"
            )
        }
    }
}