def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any

    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    environment {
       cluster = 'vproappProd'
       service = 'vprofileapptasks-service-prod'
    }

    stage('Deploy to Staging ECS') {
            steps {
                script {
                    withAWS(credentials: 'awscreds', region: 'us-east-1') {
                        sh """
                        aws ecs update-service --cluster ${env.cluster} --service ${env.service} --force-new-deployment
                        """
                    }
                }
            }
        }

    

    post {

        always {

            echo 'Slack Notifications.'

            slackSend(
                channel: '#devopscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
            )
        }
    }
}


// def COLOR_MAP = [
//     'SUCCESS': 'good', 
//     'FAILURE': 'danger',
// ]

// pipeline {
//     agent any
//     tools {
//         maven "MAVEN3.9"
//         jdk "JDK17"
//     }
    
//     environment {
//         SNAP_REPO = 'vprofile-snapshot'
// 		NEXUS_USER = 'admin'
// 		NEXUS_PASS = 'admin'
// 		RELEASE_REPO = 'vprofile-release'
// 		CENTRAL_REPO = 'vpro-maven-central'
// 		NEXUSIP = '172.31.34.4'
// 		NEXUSPORT = '8081'
// 		NEXUS_GRP_REPO = 'vpro-maven-group'
//         NEXUS_LOGIN = 'nexuslogin'
//         SONARSERVER = 'sonarserver'
//         SONARSCANNER = 'sonarscanner'
//     }

//     stages {
//         stage('Build'){
//             steps {
//                 sh 'mvn -s settings.xml -DskipTests install'
//             }
//             post {
//                 success {
//                     echo "Now Archiving"
//                     archiveArtifacts artifacts: '**/*.war'
//                 }
//             }
//         }

//         stage('test') {
//             steps {
//                 sh 'mvn -s settings.xml test'
//             }
//         }

//         stage('Checkstyle analysis') {
//             steps {
//                 sh 'mvn -s settings.xml checkstyle:checkstyle'
//             }
//         }

//         stage('Sonar Code analysis') {
//           environment {
//            scannerHome = tool 'sonarscanner';
//           }

//           steps {
//             withSonarQubeEnv('sonarserver') {
//             // withSonarQubeEnv('${SONARSERVER}') { 
//               sh '''${scannerHome}/bin/sonar-scanner \
//                   -Dsonar.projectKey=vprofile \
//   				  -Dsonar.projectName=vprofile \
//                   -Dsonar.projectVersion=1.0 \
//                   -Dsonar.sources=src/ \
//                   -Dsonar.java.binaries=target/classes \
//                   -Dsonar.junit.reportsPath=target/surefire-reports \
//                   -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
//                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''

//             }
//           }

//         }

//         stage("Quality Gate") {
//             steps {
//                 timeout(time: 1, unit: 'HOURS') {
//                     // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
//                     // true = set pipeline to UNSTABLE, false = don't
//                     waitForQualityGate abortPipeline: true
//                 }
//             }
//         }

//         stage("Publish to Nexus") {
//          steps {
//            nexusArtifactUploader(
//             nexusVersion: 'nexus3',
//             protocol: 'http',
//             nexusUrl: "${env.NEXUSIP}:${env.NEXUSPORT}",
//             groupId: 'QA',
//             version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
//             repository: 'vprofile-release',
//             credentialsId: 'nexuslogin',
//             artifacts: [
//                 [
//                     artifactId: 'vproapp',
//                     classifier: '',
//                     file: 'target/vprofile-v2.war',
//                     type: 'war' ]
//             ]
//         )
//     }
// }

//         post {
//           always {
//             echo 'Slack Notifications.'
//             slackSend channel: '#devopscicd',
//                 color: COLOR_MAP[currentBuild.currentResult],
//                 message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
//         }
//     }

//     }
// }



//          stage("Publish to Nexus") {
//           steps {
//             nexusArtifactUploader(
//               nexusVersion: 'nexus3',
//               protocol: 'http',
//               nexusUrl: '${NEXUSIP}:${NEXUSPORT}',
//               groupId: 'QA',
//               version: "${env.BUILD_ID}-${BUILD_TIMESTAMP}",
//               repository: 'vprofile-repo',
//               credentialsId: 'nexuslogin',
//               artifacts: [
//                 [  artifactId: 'vproapp', 
//                    classifier: '', 
//                    file: 'target/vprofile-v2.war', 
//                    type: 'war'  ]
//               ]
//             )

//           }

//         }



//     }
// }

// pipeline {
//     agent any
//     tools {
//         maven "MAVEN3.9"
//         jdk "JDK17"
//     }
    
//     environment {
//         SNAP_REPO = 'vprofile-snapshot'
// 		NEXUS_USER = 'admin'
// 		NEXUS_PASS = 'admin'
// 		RELEASE_REPO = 'vprofile-release'
// 		CENTRAL_REPO = 'vpro-maven-central'
// 		NEXUSIP = '172.31.34.4'
// 		NEXUSPORT = '8081'
// 		NEXUS_GRP_REPO = 'vpro-maven-group'
//         NEXUS_LOGIN = 'nexuslogin'
//     }

//     stages {
//         stage('Build'){
//             steps {
//                 sh 'mvn -s settings.xml -DskipTests install'
            
            
//             }
//             post {
//                 success {
//                     echo "Now Archiving"
//                     archiveArtifacts artifacts: '**/*.war'
                   
//                 }
//             }
//         }

//         stage('test') {
//             steps {
//                 sh 'mvn test'
//             }
//         }

//         stage('Checkstyle analysis') {
//             steps {
//                 sh 'mvn checkstyle:checkstyle'
//             }
//         }
//     }
// }
